/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MainViewController;
import Model.CanBo;
import Model.ChucDanh;
import Model.ChucVu;
import de.javasoft.plaf.synthetica.SyntheticaPlainLookAndFeel;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DINHQUY
 */
public class CanBoSearchView extends javax.swing.JFrame {
    public int selected_index_1 = 0;
    public int selected_index_2 = 0;
    public int selected_index_3 = 0;    
    /**
     * Creates new form CanBoSearchView
     */
    String s="";
    public CanBoSearchView() {
        initComponents();
        model = new DefaultTableModel();
    }
    public CanBoSearchView(String sn){
        s = sn;
        initComponents();
        model = new DefaultTableModel();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BackBtn = new javax.swing.JButton();
        PrintSearch_Btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        CB_1 = new javax.swing.JComboBox<String>();
        text_1 = new javax.swing.JTextField();
        CB_2 = new javax.swing.JComboBox();
        text_2 = new javax.swing.JTextField();
        CB_3 = new javax.swing.JComboBox();
        text_3 = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        RefreshBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BackBtn.setText("Quay Lại");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        PrintSearch_Btn.setText("In");
        PrintSearch_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintSearch_BtnActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        CB_1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chọn", "cán bộ ID", "họ tên", "giới tính", "năm sinh", "chức vụ", "chức danh", "nơi công tác", "địa chỉ", "email", "số điện thoại" }));
        CB_1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CB_1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CB_1FocusLost(evt);
            }
        });
        CB_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_1ActionPerformed(evt);
            }
        });

        text_1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                text_1FocusGained(evt);
            }
        });
        text_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_1ActionPerformed(evt);
            }
        });
        text_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_1KeyPressed(evt);
            }
        });

        CB_2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chọn", "cán bộ ID", "họ tên", "giới tính", "năm sinh", "chức vụ", "chức danh", "nơi công tác", "địa chỉ", "email", "số điện thoại" }));
        CB_2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CB_2FocusLost(evt);
            }
        });
        CB_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_2ActionPerformed(evt);
            }
        });

        text_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_2KeyPressed(evt);
            }
        });

        CB_3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chọn", "cán bộ ID", "họ tên", "giới tính", "năm sinh", "chức vụ", "chức danh", "nơi công tác", "địa chỉ", "email", "số điện thoại" }));
        CB_3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CB_3FocusLost(evt);
            }
        });

        text_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_3KeyPressed(evt);
            }
        });

        SearchBtn.setText("Tìm");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        RefreshBtn.setText("Tải Lại");
        RefreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CB_1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(RefreshBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(SearchBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CB_1, CB_2, CB_3});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(CB_1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CB_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CB_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(RefreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {CB_1, CB_2, CB_3});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PrintSearch_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrintSearch_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private DefaultTableModel model;
    CanBo canbo = new CanBo();
    ChucVu cv = new ChucVu();
    ChucDanh cd = new ChucDanh();
    
    public void Binding(Vector data) {
        
        Vector clums = new Vector();
        clums.add("CanBoID");
        clums.add("HoVaTen");
        clums.add("NgaySinh");
        clums.add("GioiTinh");
        clums.add("Chuc vu");
        clums.add("Chuc Danh");
        clums.add("NoiCongTac");
        clums.add("DiaChi");
        clums.add("SoDienThoai");
        clums.add("Email");
        
        model.setColumnIdentifiers(clums);
        DefaultTableModel model = new DefaultTableModel(data, clums);
        jTable1.setModel(model);

    }
    

    
    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
    }//GEN-LAST:event_SearchBtnActionPerformed
    
    
    
        
 
    
    private void text_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_1ActionPerformed
    
    }//GEN-LAST:event_text_1ActionPerformed

    private void text_1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_1KeyPressed



    }//GEN-LAST:event_text_1KeyPressed

    private void text_2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_2KeyPressed



    }//GEN-LAST:event_text_2KeyPressed

    private void text_3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_3KeyPressed


    }//GEN-LAST:event_text_3KeyPressed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        
        Main m = new Main(s);
        m.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_BackBtnActionPerformed

    private void text_1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_1FocusGained
        // TODO add your handling code here:
        text_1.setText("");
    }//GEN-LAST:event_text_1FocusGained

    private void CB_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_2ActionPerformed

    private void CB_1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CB_1FocusGained


    }//GEN-LAST:event_CB_1FocusGained

    private void CB_1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CB_1FocusLost

    }//GEN-LAST:event_CB_1FocusLost

    private void RefreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshBtnActionPerformed

    
    }//GEN-LAST:event_RefreshBtnActionPerformed

    private void CB_2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CB_2FocusLost

    }//GEN-LAST:event_CB_2FocusLost

    private void CB_3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CB_3FocusLost

    }//GEN-LAST:event_CB_3FocusLost

    private void CB_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_1ActionPerformed

    private void PrintSearch_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintSearch_BtnActionPerformed
        JTable.PrintMode mode =  JTable.PrintMode.FIT_WIDTH;
                                        
        try {
            boolean complete = jTable1.print(mode);
            if (complete) {
                JOptionPane.showMessageDialog(this,
                                              "Printing Complete",
                                              "Printing Result",
                                              JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                                              "Printing Cancelled",
                                              "Printing Result",
                                              JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (PrinterException pe) {
            JOptionPane.showMessageDialog(this,
                                          "Printing Failed: " + pe.getMessage(),
                                          "Printing Result",
                                          JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_PrintSearch_BtnActionPerformed
    
    public void SearchBtnListener(ActionListener listenerForGetBtn) {
        SearchBtn.addActionListener(listenerForGetBtn);
    }
    
    public void RefreshBtnListener(ActionListener listenerForGetBtn) {
        RefreshBtn.addActionListener(listenerForGetBtn);
    }
    public void PrintBtnListener(ActionListener listenerForGetBtn) {
        PrintSearch_Btn.addActionListener(listenerForGetBtn);
    }
    public void BackBtnListener(ActionListener listenerForGetBtn) {
        BackBtn.addActionListener(listenerForGetBtn);
    }
    public void Combobox_1Listener(ActionListener listenerForGetBtn) {
        CB_1.addActionListener(listenerForGetBtn);
    }
    public void Combobox_2Listener(ActionListener listenerForGetBtn) {
        CB_2.addActionListener(listenerForGetBtn);
    }
    public void Conbobox_3Listener(ActionListener listenerForGetBtn) {
        CB_3.addActionListener(listenerForGetBtn);
    }
    
    public JComboBox<String> getCB_1() {
        return CB_1;
    }

    public void setCB_1(JComboBox<String> CB_1) {
        this.CB_1 = CB_1;
    }

    public JComboBox getCB_2() {
        return CB_2;
    }

    public void setCB_2(JComboBox CB_2) {
        this.CB_2 = CB_2;
    }

    public JComboBox getCB_3() {
        return CB_3;
    }

    public void setCB_3(JComboBox CB_3) {
        this.CB_3 = CB_3;
    }

    public JTextField getText_1() {
        return text_1;
    }

    public void setText_1(JTextField text_1) {
        this.text_1 = text_1;
    }

    public JTextField getText_2() {
        return text_2;
    }

    public void setText_2(JTextField text_2) {
        this.text_2 = text_2;
    }

    public JTextField getText_3() {
        return text_3;
    }

    public void setText_3(JTextField text_3) {
        this.text_3 = text_3;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            try {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
                * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                */
                UIManager.setLookAndFeel(new SyntheticaPlainLookAndFeel());
                //</editor-fold>
            } catch (ParseException ex) {
                Logger.getLogger(CanBoSearchView.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(CanBoSearchView.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CanBoSearchView().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BackBtn;
    public javax.swing.JComboBox<String> CB_1;
    public javax.swing.JComboBox CB_2;
    public javax.swing.JComboBox CB_3;
    public javax.swing.JButton PrintSearch_Btn;
    public javax.swing.JButton RefreshBtn;
    public javax.swing.JButton SearchBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    public javax.swing.JTextField text_1;
    public javax.swing.JTextField text_2;
    public javax.swing.JTextField text_3;
    // End of variables declaration//GEN-END:variables
}
